[package]
name = "clipcat"
version = "0.5.0"
authors = ["xrelkd <46590321+xrelkd@users.noreply.github.com>", "Icelk <main@icelk.dev>", "bootstrap-prime <bootstrap.prime@gmail.com>"]
edition = "2021"

[features]
all = ["clipcatd", "clipcatctl", "clipcat-menu", "clipcat-notify"]
default = ["clipcatd", "clipcatctl", "clipcat-menu"]

app = ["app_dirs", "structopt", "toml", "tracing-subscriber", "tracing-futures"]
monitor = ["copypasta"]
daemon = [
  "daemonize", "libc",
  "tracing-subscriber", "tracing-journald",
  "tokio/signal", "serde_json",
  "bincode"
]
external_editor = ["tokio/process"]
builtin_finder = ["skim"]

x11 = ["copypasta/x11"]
wayland = ["copypasta/wayland"]

clipcatd = ["app", "monitor", "daemon"]
clipcatctl = ["app", "tokio/process", "tokio/io-std", "tokio/fs", "external_editor"]
clipcat-menu = ["app", "tokio/process", "external_editor", "builtin_finder"]
clipcat-notify = ["structopt", "monitor"]

[lib]
name = "clipcat"
path = "src/lib.rs"

[[bin]]
name = "clipcatd"
path = "src/bin/clipcatd/main.rs"
required-features = ["clipcatd"]

[[bin]]
name = "clipcatctl"
path = "src/bin/clipcatctl/main.rs"
required-features = ["clipcatctl"]

[[bin]]
name = "clipcat-menu"
path = "src/bin/clipcat-menu/main.rs"
required-features = ["clipcat-menu"]

[[bin]]
name = "clipcat-notify"
path = "src/bin/clipcat-notify/main.rs"
required-features = ["clipcat-notify"]

[dependencies]
futures = "0.3"
tokio = { version = "1", features = ["rt-multi-thread", "sync"] }

snafu = "0.6"

tonic = "0.4"
prost = "0.7"
http = "0.2"

tracing = "0.1"
tracing-subscriber = { version = "0.2", optional = true }
tracing-journald = { version = "0.1", optional = true }
tracing-futures = { version = "0.2", optional = true }

structopt = { version = "0.3", optional = true }
app_dirs = { version = "1", optional = true }
toml = { version = "0.5", optional = true }

serde = { version = "1", features = ["derive"] }
serde_with = "1"
serde_json = { version = "1", optional = true }

copypasta = { version = "0.7.1", optional = true }

bincode = { version = "1", optional = true }

libc = { version = "0.2", optional = true }
daemonize = { version = "0.4", optional = true }

skim = { version = "0.9", optional = true }

[build-dependencies]
tonic-build = { version = "0.4", features = ["prost"] }

[profile.release]
opt-level = 3
lto = true

[profile.dev]
opt-level = 0
